const findQAs = (v1) => {
    const ans = {
        personalQA: [{}],
        socialQA: [{}],
        academicQA: [{}],
        occupationalQA: [{}],
        recreationalQA: [{}]
    }
    console.log("[findQAs] - Function called to return questions for " + v1)
    if (v1 == "preprimary") {
        ans.personalQA = [{ question: "Chews and swallows solid food when placed in his mouth", answer: "" },
        { question: "Holds and drinks water or milk or juice from a glass or cup", answer: "" },
        { question: "Eats by self with fingers when food is mixed and given", answer: "" },
        { question: "Sits on potty or squats to pass urine or stools", answer: "" },
        { question: "Indicates verbally or through gestures the need to go to the toilet", answer: "" },
        { question: "Takes off under clothes to use toilet (when unbuttoned/ pulling clastic pants)", answer: "" },
        { question: "Brushes teeth either with tooth brush or with a finger using tooth paste or tooth powder", answer: "" },
        { question: "Cooperates while being bathed extending hands/legs when told", answer: "" },
        { question: "Takes off clothes (inlcuding under garments) when unbuttoned", answer: "" },
        { question: "Wears undergarments", answer: "" },
        { question: "Cleans nose with a handkerchief", answer: "" },
        { question: "Washes hands before eating snacks or food or after using toilet or when hands are dirty", answer: "" },
        { question: "Wipes with a towel after bath", answer: "" },
        { question: "Peels off fruits such as orange and banana before eating", answer: "" },
        { question: "Eats with an appropriate side dish such as bread & jam, chapati & curry, Idli & chutncy", answer: "" },
        { question: "Mixes and eats by self without spilling", answer: "" },
        { question: "Wipes hand and mouth with a towel after washing", answer: "" },
        { question: "Wears slippers", answer: "" },
        { question: "Wears shoes without shoe lace or buckle", answer: "" }]
        ans.socialQA = [{ question: "Moves head or eyes to see persons moving near him or in the room", answer: "" },
        { question: "Responds to his name by stopping an activity or looking at the person when called", answer: "" },
        { question: "Goes to a familiar person when asked to come near him", answer: "" },
        { question: "Smiles when other person smiles at him", answer: "" },
        { question: "Plays with two other children cooperatively", answer: "" },
        { question: "Waits for his turn in the classroom, play ground, dining room", answer: "" },
        { question: "Shares his things (pencil, books, eraser, toys and eatables) when requested by his classmates or others", answer: "" },
        { question: "Greets teachers or elders in school or at home", answer: "" },
        { question: "Differentiates strangers from familiar people", answer: "" },
        { question: "Expresses anger displeasure by vocalizations (shouting/turning away/ screaming) other than crying", answer: "" },
        { question: "Stops momentarily an activity when said 'no'", answer: "" },
        { question: "Uses vocal sounds/gestures/actions to call a person/to get attention of others", answer: "" },
        { question: "Responds appropriately to words alongwith gestures such as come, up, go, bye-bye, etc", answer: "" },
        { question: "Uses gestures such as shaking head for 'no', head nodding for 'yes' hand gesture for 'come', 'give', 'sleep', 'tata'", answer: "" },
        { question: "Follows simple verbal requests with gestures such as 'give', 'I will take' (response could be gestural or verbal)", answer: "" },
        { question: "Uses words such as 'mama', 'nana', 'deedi', 'bow bow', etc", answer: "" },
        { question: "Follows simple commands without gestures like 'where is the ball', 'put that down', 'bring the ball", answer: "" },
        { question: "Answers questions such as 'how does a car go', 'how does an aeroplane go', 'how do you apply face powder', (responses inmiming fashion)", answer: "" },
        { question: "Identifies persons by pointing or naming upon request (eg, uncle, aunty, sister, brother, etc.)", answer: "" },
        { question: "Asks for desired objects using gestures/alongwith vocalizations", answer: "" },
        { question: "Tells him name when asked", answer: "" },
        { question: "Gestures/says suitably for Namaste/salam/good morning", answer: "" }]
        ans.academicQA = [
            { question: "Points/shows body parts (head, nose, cycs, cars, hands, legs) when requested.", answer: "" },
            { question: "Names body parts when pointed to", answer: "" },
            { question: "Paints to 10 comman objects with which he has to interact in his/her home environment (eg.rice, dall, chapati, light, fan, mat, table, chair, shirt/frock, shorts/pants,etc.), when asked or when he wants", answer: "" },
            { question: "Says orally the names of the 10 common objects when shown when he wants.", answer: "" },
            { question: "Holds pencil and scribbles", answer: "" },
            { question: "Colours with a crayon within a given diagram", answer: "" },
            { question: "Traces on the given diagram", answer: "" },
            { question: "Cooperates while being bathed extending hands/legs when told", answer: "" },
            { question: "Copics a given figure/diagram", answer: "" },
            { question: "Groups common colours (red, green, blur, yellow) when given a group of coloured objects", answer: "" },
            { question: "Groups objects according to the size (big and small, long and short)", answer: "" },
            { question: "Gives objects/pictures of common colours when asked", answer: "" },
            { question: "Names common colours. (red, green, blue, yellow)", answer: "" },
            { question: "Points to the objects which are big and small/long and short upon request", answer: "" },
            { question: "Tells the size of the ohjeets (big & small, long & short)", answer: "" },
            { question: "Points to sets of objects to show more/less quantity", answer: "" },
            { question: "Tells which set has moreless quantity", answer: "" },
            { question: "Points to containers with either solids/liquids to show full and empty", answer: "" },
            { question: "Fells when a container is shown cither full or empty with or without liquid or solid", answer: "" },
            { question: "Rete counis upto 5", answer: "" },
            { question: "Counts and gives objects upto 5 when not asked sequentially", answer: "" },
            { question: "Counts and gives objects upto 10 when not asked sequentially.", answer: "" },
            { question: "Shows a numeral and places value when not asked sequentially", answer: "" },
            { question: "Names upto 5 numbers when not asked sequentially", answer: "" },
            { question: "Writes numerals upto 5 in a sequence", answer: "" },
            { question: "Writes numerals upto 5 when given dictation not sequentially", answer: "" },
            { question: "Points to alphabets (English/regional language) on a chart not asked sequentially (3 letter words in case of sight word icaching)", answer: "" },
            { question: "Names alphabets when asked not sequentially (3 letter words in case of sight word teaching)", answer: "" },
            { question: "Writes alphabets when given dictation (3 letter words in case of sight word teaching)", answer: "" },
            { question: "Identifies a clock or wrist watch", answer: "" },
            { question: "Tells points to when asked the use of clock or wrist watch", answer: "" },
            { question: "Differentiates money from other objects", answer: "" },
            { question: "Tells points to when asked the use of money", answer: "" },
            { question: "Groups Rs. 1, 2, 5 notes when given", answer: "" },
            { question: "Grck 1, 2, 5 rupee notes when asked", answer: "" },
            { question: "Points/tells when asked by showing Rs.1, 2, 5 notes", answer: "" },
            { question: "Counts and gives 1 rupee notes upto Rs.5 when asked", answer: "" },
            { question: "Points to atleast 5 pictures of animals when asked)", answer: "" },
            { question: "Names atleast 5 animals when shown pictures", answer: "" },
            { question: "Points to atleast 5 pictures of fruits when asked", answer: "" },
            { question: "Names atleast 5 fruits when shown pictures", answer: "" },
            { question: "Tells/points to the clothes (frock, shorts, shirt, T-shirt)he/she wears when asked", answer: "" },
            { question: "Uses words or gestures for 'now and later when necessary", answer: "" },
            { question: "Identifies/Names the various means of transport (cycle, auto, cycle rikshaw, bus, car, lorry, acroplane, train)", answer: "" },]
        ans.occupationalQA = [
            { question: "Dusts with a duster the furniture in the classroom and home", answer: "" },
            { question: "Washes glasses and plates before and after meals.", answer: "" },
            { question: "Wipes glasses and plates with a cloth after washing", answer: "" },
            { question: "Folds small clothes (such as hand towel/panties).", answer: "" }]
        ans.recreationalQA = [{ question: "Watches T.V.Advertisements(indoor)", answer: "" },
        { question: "Dances/claps/taps with rhythm of music in Radio or T.V. (indoor)", answer: "" },
        { question: "Plays with block assembling and dismantling (indoor)", answer: "" },
        { question: "Colours with pencils or crayons (indoor)", answer: "" },
        { question: "Plays make believe games pretending to be teacher, mummy, daddy or elder sibling going to school/household keeping (indoor)", answer: "" },
        { question: "Arranges own things in their appropriate places, in a given room (indoor)", answer: "" },
        { question: "Brushes teeth either with tooth brush or with a finger using tooth paste or tooth powder (indoor)", answer: "" },
        { question: "Sees pictures in magazines without tearing the book (indoor)", answer: "" },//Sees pictures in magazines without tearing the book
        { question: "Plays with ball", answer: "" },
        { question: "Plays running and catching game/runs a race/duck walking/frog jumping, etc", answer: "" },
        { question: "Climbs jungle gym etc", answer: "" },
        { question: "Sand play", answer: "" },
        { question: "Water play", answer: "" },
        { question: "Plays hide and seek game/passing the parcel/musical chairs, etc", answer: "" },
        { question: "Plays on a slide", answer: "" },
        { question: "Swings on a swing", answer: "" }]
    }
    else if (v1 == "primary1") {
        ans.personalQA = [
            { question: "Walks by himself a distance of 10 feet to fetch an object.", answer: "" },
            { question: "Climbs up and down the stairs placing both feet on each step without support.", answer: "" },
            { question: "Climbs up and down the stairs placing alternate feet without support.", answer: "" },
            { question: "Turns/removes a door knob/latch/bolt and opens the door when he wants to go in/out of the room.", answer: "" },
            { question: "Cleans self after defecation.", answer: "" },
            { question: "Flushes or pours water after toileting.", answer: "" },
            { question: "Wears clothes (including under garments) (may not fix fastener).", answer: "" },
            { question: "Unfastens clothes: a) zip,	b) press buttons, c) shirt buttons, d) hooks, e) untyingItapeI laceIribbon", answer: "" },
            { question: "Fastens clothes: a) zip, b)  press button s, c) shirt  buttons,  d) hooks, e)  tying/tape/lace/ribbon ", answer: "" },
            { question: "Eats by self a complete meal without spilling.", answer: "" },
            { question: "Asks/points to curries (vegetable, dal, sambar, etc.). When he wants more. ", answer: "" },
            { question: "Makes arrangements for lunch and dinner either on table/floor.", answer: "" },
            { question: "Takes water from the pot/tap to drink when he is thirsty.", answer: "" },
            { question: "Serves water to others.", answer: "" },
            { question: "Washes hands before eating snacks or food or after using toilet or when hands arc dirty.", answer: "" },
            { question: "Washes his/her face with soap and water.", answer: "" },
            { question: "Wipes hands and face with a towel after washing.", answer: "" },
            { question: "Cleans nose with a handkerchief when needed.", answer: "" },
            { question: "Applies soap on the body while bathing", answer: "" },
            { question: "Applies powder (and fixes bindi - in case of girls).", answer: "" },
            { question: "Combs/ brushes hair   and put s rubber band after removing tangled hair (in case of girls).", answer: "" }]
        ans.socialQA = [
            { question: "When given a chance makes a choice between two activities or between two items.", answer: "" },
            { question: "Performs the activity requested by teachers and parents.", answer: "" },
            { question: "Asks for permission   to use a toy or other material which does not belong to him.", answer: "" },
            { question: "Participates in a group game in which 4 to 5 children are involved.", answer: "" },
            { question: "Waits for his/her turn while playing games.", answer: "" },
            { question: "Shares play material during group games.", answer: "" },
            { question: "Maintains appropriate manners when taken to social functions.", answer: "" },
            { question: "Takes care of his/her own belongings in school (Eg. School bag, lunch box, pencil box).", answer: "" },
            { question: "Defends/seeks assistance when injured or teased by others.", answer: "" },
            { question: "Recognizes that the speaker is angry, t ired, sad, happy, etc. ", answer: "" },
            { question: "Names body parts when pointed to.", answer: "" },
            { question: "Uses combination of words or gestures to express his/her need or wish.", answer: "" },
            { question: "Answers (verbally/gesturally) to question 'Whose is' by pointing to self or others correctly. ", answer: "" },
            { question: "Carries out two consecutive instructions/commands.", answer: "" },
            { question: "Names members of the family like brother, sister, aunt, uncle.", answer: "" },
            { question: "Uses 2-3 word sentence to communicate information (if nonverbal makes self understood by gestures).", answer: "" },
            { question: "Asks for help (verbally or gesturally) for personal needs.", answer: "" },
            { question: "Follows messages involving   prepositions such as under, behind, in front. (Put the bag in front of the boy).", answer: "" },
            { question: "Uses correct gender term when asked. Are you (or pointed person) a boy or girl?", answer: "" },
            { question: "Can say plural forms of names. Eg. Chairs, pencils, books.", answer: "" },
            { question: "Can follow instructions of a task without visual clues or gestures.", answer: "" }]
        ans.academicQA = [
            { question: "Reads   alphabets (English or any other regional language) when shown a chart/book. (Words incase of sight word teaching).", answer: "" },
            { question: "Reads words (vegetables, fruits, furniture, animals) seeing a picture.", answer: "" },
            { question: "Reads 2 - 3 letter words without a clue (picture) (about 10).", answer: "" },
            { question: "Reads his/her name.", answer: "" },
            { question: "Reads his/her friend 's names in his/her class.", answer: "" },
            { question: "Reads four sign boards which are essential for independent mobility.", answer: "" },
            { question: "Writes his/her name.", answer: "" },
            { question: "Writes names of words (vegetables, fruits, animals, furniture, clothes).", answer: "" },
            { question: "Tells functions of sense organs.", answer: "" },
            { question: "Counts and gives objects upt o 10 when not asked sequentially.", answer: "" },
            { question: "Shows a numeral when not asked sequentially upto 10", answer: "" },
            { question: "Names numbers upto 10 when not asked sequentially.", answer: "" },
            { question: "Writes numerals upto 10 when given dictation randomly.", answer: "" },
            { question: "Writes numerals upto 10 in a logical sequence.", answer: "" },
            { question: "Writes missing numbers before and after upto 10.", answer: "" },
            { question: "Does simple addition within 10 with objects (without paper).	", answer: "" },
            { question: "Does simple addition within 10 on paper using slash marks. ", answer: "" },
            { question: "Gives exact number of objects when asked upto 20.", answer: "" },
            { question: "Expands the numbers from 11-20 (Eg. 11 = 10 & 1).", answer: "" },
            { question: "Points to numerals upto 2", answer: "" },
            { question: "When not asked sequentially.", answer: "" },
            { question: "Names ·numbers  upto 2", answer: "" },
            { question: "When not asked sequentially.", answer: "" },
            { question: "Writes numerals upto 20 when given dictation.", answer: "" },
            { question: "Writes numerals upto 20 in a sequence.", answer: "" },
            { question: "Writes missing numbers after and before upto 20. ", answer: "" },
            { question: "Counts in tens upto 100 (10, 20, 30,..... 100).", answer: "" },
            { question: "Groups in tens to make 20, 30,100.", answer: "" },
            { question: "Associates time with daily activities.", answer: "" },
            { question: "Tells/shows on a calendar/chart the name of the day when asked what day is today, what day will be tomorrow and what day was yesterday.", answer: "" },
            { question: "Tells/gestures in order what he does from morning till he goes to bed.", answer: "" },
            { question: "Tells his/her age/points to self when asked who is .... ", answer: "" },
            { question: "Tells/gestures the number of days in a week.", answer: "" },
            { question: "Tells the number of months in a year.", answer: "" },
            { question: "Indicates the date on the calendar.", answer: "" },
            { question: "Changes the date and month on a calendar stand correctly.", answer: "" },
            { question: "Tells the position of long and short hand on a clock when asked.", answer: "" },
            { question: "Shows on a clock time in hours when asked.", answer: "" },
            { question: "Tells time in hours seeing a clock/wrist watch.", answer: "" },
            { question: "Shows on a clock the time in half hours (7:30, 8:30).", answer: "" },
            { question: "Tells time in half hour (4:30, 5:30) seeing a clock/wrist watch.", answer: "" },
            { question: "Gets ready to come to school in time.", answer: "" },
            { question: "Identifies coins (1 rupee, 2 rupees 5 and l0).", answer: "" },
            { question: "Tells names of coins:", answer: "" },
            { question: "Identifies rupee notes (Rs.1, 2 upto 10).", answer: "" },
            { question: "Counts 1 rupee notes to give a sum of Rs.8, IO, 15, 20, etc.", answer: "" },
            { question: "Groups Rs.IO notes to give 20, 30, 40,	100.", answer: "" },
            { question: "Gives change lo Rs.IO using 5 rupee notes (5+5).", answer: "" },
            { question: "Gives change to Rs. IO, 20, 50 using a combination of Rs. 5 & Rs. IO notes.", answer: "" },
            { question: "Tells names of rupee notes.", answer: "" },
            { question: "Tells how many cups/glasses of water, rice/dall are required to fill a given utensil.", answer: "" },
            { question: "Measure the required cups of water for making tea.", answer: "" },
            { question: "Posts letter in the post box.", answer: "" },
            { question: "Tells his parents/family members when he feels sick.", answer: "" },
            { question: "Identifies the various means of transport (cycle, auto, cycle rikshaw, bus, car, lorry, aeroplane, train).", answer: "" },
            { question: "Names various means of transport.", answer: "" },
            { question: "Gets in and gets down from the desired bus when bus stops in the bus stop.", answer: "" },]
        ans.occupationalQA = [
            { question: "Dusts with a duster cloth the furniture and the other items in the house.", answer: "" },
            { question: "Sorts out vegetales and places them in respective container/ baskets/ in a fridge.", answer: "" },
            { question: "Places plates and glass suitably on the dining table/floor for breakfast/ lunch/dinner, when told.", answer: "" },
            { question: "Washes plates and glass·es after eating food/snacks.", answer: "" },
            { question: "Peels vegetables such as beans, onions, boiled potatoes, peas, etc. where knife I scrapper are not used.", answer: "" },
            { question: "Carries water in a small   bucket  from the tap or when required/ asked by family members.", answer: "" },
            { question: "Stacks utensils in the kitchen after washing.", answer: "" },
            { question: "Serves plates with snacks/food to family members.", answer: "" },
            { question: "Separates leaves in  the leafy vegetables.", answer: "" },
            { question: "Helps mother in kitchen  in bringing  cooking items such as vegetables/ingredients, measuring water  for making tea/ coffee when told.", answer: "" }]
        ans.recreationalQA = [
            { question: "Plays common games like snakes & ladder, five stones, with  2-3 children (with  only 2 specific rules).", answer: "" },
            { question: "Watches T.V. programmes for 15 lo 30 minutes.", answer: "" },
            { question: "Builds blocks to copy a given model (3 to 8 pieces).", answer: "" },
            { question: "Draws simple figures and  colours them.", answer: "" },
            { question: "Cuts and pastes   pictures from old magazines to make a scrap book\collage work  (when assisted while cutting).", answer: "" },
            { question: "Collects  stamps/stickers.", answer: "" },
            { question: "Assembles (Logo) games/puzzle.", answer: "" },
            { question: "Looks through  picture  books  or  comics.", answer: "" },
            { question: "Arranges room, by placing objects in their respective place.", answer: "" },
            { question: "Feeds and  cares for  pets (under supervision).", answer: "" },
            { question: "Plays by passing/throwing and catching the ball.", answer: "" },
            { question: "Flies kites, plays marble games.", answer: "" },
            { question: "Plays games like,   police and thief, land and sea, four corners or seven stones.", answer: "" },
            { question: "Waters plants.", answer: "" },
            { question: "Goes for a walk outside or visit friends house alone in same area I colony of living.", answer: "" },
            { question: "Plays aiming of darts at the bull's eye/bucketing the ball, etc.", answer: "" },
            { question: "Climbs·jungl e gym, trees or other similar structures.", answer: "" },
            { question: "Plays hopping game governed by rules.", answer: "" },
            { question: "Goes with adults for shopping.", answer: "" },
            { question: "Goes out  to restaurant/theatres  with  adults.", answer: "" }]
    }
    else if (v1 == "primary2") {
        ans.personalQA = [
            { question: "Walks by himself a distance of 10 feet to fetch an object.", answer: "" },
            { question: "Climbs up and down the stairs placing both feet on each step without support.", answer: "" },
            { question: "Climbs up and down the stairs placing alternate feet without support.", answer: "" },
            { question: "Turns/removes a door knob/latch/bolt and opens the door when he wants to go in/out of the room.", answer: "" },
            { question: "Cleans self after defecation.", answer: "" },
            { question: "Flushes or pours water after toileting.", answer: "" },
            { question: "Wears clothes (including under garments) (may not fix fastener).", answer: "" },
            { question: "Unfastens clothes: a) zip,	b) press buttons, c) shirt buttons, d) hooks, e) untyingItapeI laceIribbon", answer: "" },
            { question: "Fastens clothes: a) zip, b)  press button s, c) shirt  buttons,  d) hooks, e)  tying/tape/lace/ribbon ", answer: "" },
            { question: "Eats by self a complete meal without spilling.", answer: "" },
            { question: "Asks/points to curries (vegetable, dal, sambar, etc.). When he wants more. ", answer: "" },
            { question: "Makes arrangements for lunch and dinner either on table/floor.", answer: "" },
            { question: "Takes water from the pot/tap to drink when he is thirsty.", answer: "" },
            { question: "Serves water to others.", answer: "" },
            { question: "Washes hands before eating snacks or food or after using toilet or when hands arc dirty.", answer: "" },
            { question: "Washes his/her face with soap and water.", answer: "" },
            { question: "Wipes hands and face with a towel after washing.", answer: "" },
            { question: "Cleans nose with a handkerchief when needed.", answer: "" },
            { question: "Applies soap on the body while bathing", answer: "" },
            { question: "Applies powder (and fixes bindi - in case of girls).", answer: "" },
            { question: "Combs/ brushes hair   and put s rubber band after removing tangled hair (in case of girls).", answer: "" }]
        ans.socialQA = [
            { question: "When given a chance makes a choice between two activities or between two items.", answer: "" },
            { question: "Performs the activity requested by teachers and parents.", answer: "" },
            { question: "Asks for permission   to use a toy or other material which does not belong to him.", answer: "" },
            { question: "Participates in a group game in which 4 to 5 children are involved.", answer: "" },
            { question: "Waits for his/her turn while playing games.", answer: "" },
            { question: "Shares play material during group games.", answer: "" },
            { question: "Maintains appropriate manners when taken to social functions.", answer: "" },
            { question: "Takes care of his/her own belongings in school (Eg. School bag, lunch box, pencil box).", answer: "" },
            { question: "Defends/seeks assistance when injured or teased by others.", answer: "" },
            { question: "Recognizes that the speaker is angry, t ired, sad, happy, etc. ", answer: "" },
            { question: "Names body parts when pointed to.", answer: "" },
            { question: "Uses combination of words or gestures to express his/her need or wish.", answer: "" },
            { question: "Answers (verbally/gesturally) to question 'Whose is' by pointing to self or others correctly. ", answer: "" },
            { question: "Carries out two consecutive instructions/commands.", answer: "" },
            { question: "Names members of the family like brother, sister, aunt, uncle.", answer: "" },
            { question: "Uses 2-3 word sentence to communicate information (if nonverbal makes self understood by gestures).", answer: "" },
            { question: "Asks for help (verbally or gesturally) for personal needs.", answer: "" },
            { question: "Follows messages involving   prepositions such as under, behind, in front. (Put the bag in front of the boy).", answer: "" },
            { question: "Uses correct gender term when asked. Are you (or pointed person) a boy or girl?", answer: "" },
            { question: "Can say plural forms of names. Eg. Chairs, pencils, books.", answer: "" },
            { question: "Can follow instructions of a task without visual clues or gestures.", answer: "" }]
        ans.academicQA = [
            { question: "Reads   alphabets (English or any other regional language) when shown a chart/book. (Words incase of sight word teaching).", answer: "" },
            { question: "Reads words (vegetables, fruits, furniture, animals) seeing a picture.", answer: "" },
            { question: "Reads 2 - 3 letter words without a clue (picture) (about 10).", answer: "" },
            { question: "Reads his/her name.", answer: "" },
            { question: "Reads his/her friend 's names in his/her class.", answer: "" },
            { question: "Reads four sign boards which are essential for independent mobility.", answer: "" },
            { question: "Writes his/her name.", answer: "" },
            { question: "Writes names of words (vegetables, fruits, animals, furniture, clothes).", answer: "" },
            { question: "Tells functions of sense organs.", answer: "" },
            { question: "Counts and gives objects upt o 10 when not asked sequentially.", answer: "" },
            { question: "Shows a numeral when not asked sequentially upto 10", answer: "" },
            { question: "Names numbers upto 10 when not asked sequentially.", answer: "" },
            { question: "Writes numerals upto 10 when given dictation randomly.", answer: "" },
            { question: "Writes numerals upto 10 in a logical sequence.", answer: "" },
            { question: "Writes missing numbers before and after upto 10.", answer: "" },
            { question: "Does simple addition within 10 with objects (without paper).	", answer: "" },
            { question: "Does simple addition within 10 on paper using slash marks. ", answer: "" },
            { question: "Gives exact number of objects when asked upto 20.", answer: "" },
            { question: "Expands the numbers from 11-20 (Eg. 11 = 10 & 1).", answer: "" },
            { question: "Points to numerals upto 2", answer: "" },
            { question: "When not asked sequentially.", answer: "" },
            { question: "Names ·numbers  upto 2", answer: "" },
            { question: "When not asked sequentially.", answer: "" },
            { question: "Writes numerals upto 20 when given dictation.", answer: "" },
            { question: "Writes numerals upto 20 in a sequence.", answer: "" },
            { question: "Writes missing numbers after and before upto 20. ", answer: "" },
            { question: "Counts in tens upto 100 (10, 20, 30,..... 100).", answer: "" },
            { question: "Groups in tens to make 20, 30,100.", answer: "" },
            { question: "Associates time with daily activities.", answer: "" },
            { question: "Tells/shows on a calendar/chart the name of the day when asked what day is today, what day will be tomorrow and what day was yesterday.", answer: "" },
            { question: "Tells/gestures in order what he does from morning till he goes to bed.", answer: "" },
            { question: "Tells his/her age/points to self when asked who is .... ", answer: "" },
            { question: "Tells/gestures the number of days in a week.", answer: "" },
            { question: "Tells the number of months in a year.", answer: "" },
            { question: "Indicates the date on the calendar.", answer: "" },
            { question: "Changes the date and month on a calendar stand correctly.", answer: "" },
            { question: "Tells the position of long and short hand on a clock when asked.", answer: "" },
            { question: "Shows on a clock time in hours when asked.", answer: "" },
            { question: "Tells time in hours seeing a clock/wrist watch.", answer: "" },
            { question: "Shows on a clock the time in half hours (7:30, 8:30).", answer: "" },
            { question: "Tells time in half hour (4:30, 5:30) seeing a clock/wrist watch.", answer: "" },
            { question: "Gets ready to come to school in time.", answer: "" },
            { question: "Identifies coins (1 rupee, 2 rupees 5 and l0).", answer: "" },
            { question: "Tells names of coins:", answer: "" },
            { question: "Identifies rupee notes (Rs.1, 2 upto 10).", answer: "" },
            { question: "Counts 1 rupee notes to give a sum of Rs.8, IO, 15, 20, etc.", answer: "" },
            { question: "Groups Rs.IO notes to give 20, 30, 40,	100.", answer: "" },
            { question: "Gives change lo Rs.IO using 5 rupee notes (5+5).", answer: "" },
            { question: "Gives change to Rs. IO, 20, 50 using a combination of Rs. 5 & Rs. IO notes.", answer: "" },
            { question: "Tells names of rupee notes.", answer: "" },
            { question: "Tells how many cups/glasses of water, rice/dall are required to fill a given utensil.", answer: "" },
            { question: "Measure the required cups of water for making tea.", answer: "" },
            { question: "Posts letter in the post box.", answer: "" },
            { question: "Tells his parents/family members when he feels sick.", answer: "" },
            { question: "Identifies the various means of transport (cycle, auto, cycle rikshaw, bus, car, lorry, aeroplane, train).", answer: "" },
            { question: "Names various means of transport.", answer: "" },
            { question: "Gets in and gets down from the desired bus when bus stops in the bus stop.", answer: "" },]
        ans.occupationalQA = [
            { question: "Dusts with a duster cloth the furniture and the other items in the house.", answer: "" },
            { question: "Sorts out vegetales and places them in respective container/ baskets/ in a fridge.", answer: "" },
            { question: "Places plates and glass suitably on the dining table/floor for breakfast/ lunch/dinner, when told.", answer: "" },
            { question: "Washes plates and glass·es after eating food/snacks.", answer: "" },
            { question: "Peels vegetables such as beans, onions, boiled potatoes, peas, etc. where knife I scrapper are not used.", answer: "" },
            { question: "Carries water in a small   bucket  from the tap or when required/ asked by family members.", answer: "" },
            { question: "Stacks utensils in the kitchen after washing.", answer: "" },
            { question: "Serves plates with snacks/food to family members.", answer: "" },
            { question: "Separates leaves in  the leafy vegetables.", answer: "" },
            { question: "Helps mother in kitchen  in bringing  cooking items such as vegetables/ingredients, measuring water  for making tea/ coffee when told.", answer: "" }]
        ans.recreationalQA = [
            { question: "Plays common games like snakes & ladder, five stones, with  2-3 children (with  only 2 specific rules).", answer: "" },
            { question: "Watches T.V. programmes for 15 lo 30 minutes.", answer: "" },
            { question: "Builds blocks to copy a given model (3 to 8 pieces).", answer: "" },
            { question: "Draws simple figures and  colours them.", answer: "" },
            { question: "Cuts and pastes   pictures from old magazines to make a scrap book\collage work  (when assisted while cutting).", answer: "" },
            { question: "Collects  stamps/stickers.", answer: "" },
            { question: "Assembles (Logo) games/puzzle.", answer: "" },
            { question: "Looks through  picture  books  or  comics.", answer: "" },
            { question: "Arranges room, by placing objects in their respective place.", answer: "" },
            { question: "Feeds and  cares for  pets (under supervision).", answer: "" },
            { question: "Plays by passing/throwing and catching the ball.", answer: "" },
            { question: "Flies kites, plays marble games.", answer: "" },
            { question: "Plays games like,   police and thief, land and sea, four corners or seven stones.", answer: "" },
            { question: "Waters plants.", answer: "" },
            { question: "Goes for a walk outside or visit friends house alone in same area I colony of living.", answer: "" },
            { question: "Plays aiming of darts at the bull's eye/bucketing the ball, etc.", answer: "" },
            { question: "Climbs·jungl e gym, trees or other similar structures.", answer: "" },
            { question: "Plays hopping game governed by rules.", answer: "" },
            { question: "Goes with adults for shopping.", answer: "" },
            { question: "Goes out  to restaurant/theatres  with  adults.", answer: "" }]
    } else {
        console.log("[findQAs] - Did not find the questions for " + v1)
    }
    // console.log(ans)
    return ans
}

module.exports = findQAs